### ISSUE TITLE
Cannot customize Rubocop rules

### ISSUE THREAD

**Issue by rbclark** [sds/slim-lint#141]
Our team uses https://github.com/testdouble/standard for linting. They configure some of the rules to not match the defaults. In the pursuit of having consistent rules across ruby + slim code, I attempted to customize slim-lint using my configuration file to set one of the rules to match:

```
linters:
  RuboCop:
    Style/StringLiterals:
      Enabled: true
      EnforcedStyle: double_quotes
      ConsistentQuotesInMultiline: false
```

Unfortunately this seems to have had no effect. Am I using the wrong format or is there just no way to do this?

As a side note, it seems `haml-lint` solves this problem with an `inherits_from` directive in their configuration: https://github.com/sds/haml-lint/pull/202
