### ISSUE TITLE
invalid Do not use prefix `_` for a variable that is used.

### ISSUE THREAD

**Issue by justin808** [sds/slim-lint#3]
slim-lint app/views

```
app/views/devise/confirmations/new.html.slim:3 [W] RuboCop: Lint/UnderscorePrefixedVariableName: Do not use prefix `_` for a variable that is used.
```
I don't see any `_` variable

```
h2
  | Resend confirmation instructions
= simple_form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f|
  = f.error_notification
  = f.full_error :confirmation_token
  .form-inputs
    = f.input :email, required: true, autofocus: true
  .form-actions
    = f.button :submit, "Resend confirmation instructions"
= render "devise/shared/links"
```

**Comment by sds** [comment]
Hey @justin808, thanks for the report.

Yes, this is a bug in how we're extracting the Ruby code from the Slim template. It turns out an assumption was made that isn't valid. I'm working on a solution but a proper fix may take me some time, so for the moment you can disregard these nonsensical errors. Sorry about the confusion!

**Comment by sds** [comment]
I've released version [0.4.0](https://github.com/sds/slim-lint/releases/tag/v0.4.0) which should address a number of these issues. Let me know if you see other strange/erroneous errors!

**Comment by justin808** [comment]
@sds Looks good

Any opinions on my config file?

```
linters:
  LineLength:
    max: 120
  ConsecutiveControlStatements:
    max_consecutive: 6

  RuboCop:
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/LineLength
      - Style/AlignParameters
      - Style/BlockNesting
      - Style/FileName
      - Style/IfUnlessModifier
      - Style/IndentationConsistency
      - Style/IndentationWidth
      - Style/Next
      - Style/TrailingBlankLines
      - Style/TrailingWhitespace
      - Style/WhileUntilModifier
      - Metrics/BlockNesting

```
