### ISSUE TITLE
Feature request: enforce a consistent attributes wrapper style

### ISSUE THREAD

**Issue by cannikin** [sds/slim-lint#89]
https://www.rubydoc.info/gems/slim/frames#Attributes_wrapper

Maybe with a config option like:

```yaml
AttributesWrapper:
  enabled: true
  style: none|any|curly|round|square
```

If I can figure out how the slim parser identifies these perhaps I can submit a PR soon. :)
